#!/usr/bin/env bash
# This script display numbers 1 to 20 with specialfor 4,9, and 17 
i=1
while [ $i -le 20 ] 
do 
echo $i
case $i in
     4) 
        echo "bad luck from China"
        ;;
     9) 
        echo "bad luck in Japan"
        ;;
     17) 
        echo "bad luck from Italy"
        ;;
  esac
  ((i++))
done     
