#!/usr/bin/env bash
# This script gives information about the school file
if [ -e school ]; then 
  echo "scjool file exists"
  if [ -s school ]; then 
  echo "school file is not empty"
 els 
echo "school file is empty"
fi 
if [ -f school ]; then 
echo "school is a regular file"
fi 
else 
echo "school file does not exist"
fi  

