#!/usr/bin/env bash
#create a file with SIGTERM, SIGINT, AND SIGQUIT hattler
touch /var/run/myscript.pid
trap 'echo "I hate the kill command"; rm -f /var/run/myscript.pid' TERM
trap 'echo "Y U no love me"' INT
trap 'rm -f /var/run/myscript.pid' QUIT
while 'true'
do 
  echo "To infinity and beyond"
done
