#!/usr/bin/env bash
#manages the manage_process file using init.d 
case "$1" in
	start)
		./manage_my_process &
		echo $! > /var/run/my_process.pid
		echo "manage_my_process started"
		;;
	stop)
		kill "$(cat /var/run/my_process.pid)"
	        sudo rm -f /var/run/my_process.pid
	        echo "manage_my_process stopped"
		;;
	restart)
		kill "$(cat /var/run/my_process.pid)"
		sudo rm -f /var/run/my_process.pidi
		./manage_my_process &
		echo $! > /var/run/my_process.pid
		echo "manage_my_process restarted"
		;;
	*)
	        echo "Usage: manage_my_process {start|stop|restart}"
		;;
	esac
